package flow.typedefs;

import color.Color;

typedef Config = {
	SIM_RESOLUTION:Int,
	DYE_RESOLUTION:Int,
	DENSITY_DISSIPATION:Float,
	VELOCITY_DISSIPATION:Float,
	PRESSURE_DISSIPATION:Float,
	PRESSURE_ITERATIONS:Int,
	CURL:Int,
	SPLAT_RADIUS:Float,
	SHADING:Bool,
	COLORFUL:Bool,
	PAUSED:Bool,
	BACK_COLOR:FlowColor,
	TRANSPARENT:Bool,
	BLOOM:Bool,
	BLOOM_ITERATIONS:Int,
	BLOOM_RESOLUTION:Int,
	BLOOM_INTENSITY:Float,
	BLOOM_THRESHOLD:Float,
	BLOOM_SOFT_KNEE:Float
}
